# Spring
spring:
  application:
    name: fae-team-2-service #-ms
  profiles:
    active: local
  # Hibernate ddl auto
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  # Spring Data Rest
  data:
    rest:
      basePath: / # TODO change to ... fae-team-2-service
      return-body-on-create: true
      return-body-on-update: true
      default-media-type: application/hal+json
  # JSON Pretty Print
  jackson:
    serialization:
      indent-output: true
    deserialization:
      accept-empty-array-as-null-object: true
  #kafka: # TODO insert when using kafka
    # group-id: "fae-team-2-service"

# Server
server:
  port: 8080
  compression.enabled: true
  compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain
# Kafka-topic
# product.topic: product
