# Spring
spring:
  application:
    name: fae-team-2-service #-ms
  profiles:
    active: local
  # Hibernate ddl auto
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  # JSON Pretty Print
  jackson:
    serialization:
      indent-output: true
    deserialization:
      accept-empty-array-as-null-object: true
  kafka:
    group-id: "fae-team-2-service"
    enabled: true

# Server
server:
  port: 8080
  compression.enabled: true
  compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain
  servlet:
    context-path: /team-2
  tomcat:
    use-relative-redirects: true

# Kafka-topic
demenziellerkrankter.topic: demenziellerkrankter
zone.topic: zone
zonenabweichung.topic: zonenabweichung
positionssender.topic: positionssender
tracker.topic: tracker

# Messaging system
messaging:
  service-post-url: "http://fae-team-3-service/ausnahmesituation"
  delayBetweenRetry: 15000 #in ms
  maxAgeForRetry: 20 #in min