version: "3.7"

services:
  postgres:
    image: postgres:10.1
    volumes:
      - fae-team-2-service_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=SuperTeam123
      - POSTGRES_USER=team2
      - POSTGRES_DB=team2
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - service_internal
      - fae_backend
    ports:
      - "25565:5432"
  springboot-service:
    image: docker.nexus.archi-lab.io/archilab/fae-team-2-service
    environment:
      - TZ=Europe/Berlin
      - TEAM2_DB=postgres
      - TEAM2_DB_NAME=team2
      - TEAM2_DB_USER=team2
      - TEAM2_DB_PW=SuperTeam123
    depends_on:
      - postgres
    networks:
      - service_internal
      - fae_backend

volumes:
  fae-team-2-service_db: {}

networks:
  service_internal:
  fae_backend:
    external: true
